# Generated by Django 2.2.28 on 2024-11-17 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id_chambre', models.AutoField(primary_key=True, serialize=False)),
                ('disponibilite', models.BooleanField(default=True)),
                ('standing', models.CharField(choices=[('Standard', 'Standard'), ('Deluxe', 'Deluxe')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_personne', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=150)),
                ('telephone', models.BigIntegerField()),
                ('etat', models.CharField(max_length=50)),
                ('lieu', models.CharField(default='chambre', max_length=100)),
                ('standing', models.CharField(max_length=50)),
                ('date_fin_sejour', models.DateField()),
                ('date_debut_sejour', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut_sejour', models.DateField()),
                ('date_fin_sejour', models.DateField()),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='hotel.Chambre')),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='hotel.Client')),
            ],
        ),
        migrations.AddField(
            model_name='chambre',
            name='id_occupant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupations', to='hotel.Client'),
        ),
    ]
