# Generated by Django 2.2.28 on 2024-11-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_client_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='etat',
            field=models.CharField(choices=[('fatigué', 'Fatigué'), ('faim', 'Faim'), ('stressé', 'Stressé'), ('énergie', 'Énergie'), ('détendu', 'Détendu')], default='fatigué', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='lieu',
            field=models.CharField(choices=[('piscine', 'Piscine'), ('jacuzzi', 'Jacuzzi'), ('salle de sport', 'Salle de Sport'), ('discothèque', 'Discothèque'), ('plage', 'Plage'), ('restaurant', 'Restaurant'), ('chambre', 'Chambre')], default='chambre', max_length=100),
        ),
    ]
